blank_issues_enabled: true
contact_links:
  - name: Duet3D Community Support
    url: https://forum.duet3d.com//
    about: Please ask and answer questions here.
  - name: Duet3D Documentation
    url: https://docs.duet3d.com
    about: Detailed documentation for Duet electronics and RepRapFirmware.
